CREATE DATABASE IF NOT EXISTS exodus40lite CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'exodus40lite'@'localhost' IDENTIFIED BY 'CHANGE_ME';
GRANT ALL PRIVILEGES ON exodus40lite.* TO 'exodus40lite'@'localhost';
FLUSH PRIVILEGES;
